### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by jpasholk** [jpasholk/jekyll-uikit#15]
Chrome is throwing ssl errors for some reason.

**Comment by mwoolweaver** [comment]
It’s related to the http-* tags I’m almost certain but I could be wrong

**Comment by jpasholk** [comment]
Reverted files back to original UiKit minified versions, it bought back the missing icon in the <hr>.

SSL issues persist. 

 c81bc3a832bee48452afee217f743b1515ab86b7

**Comment by jpasholk** [comment]
Here is the error on my version:

`Mixed Content: The page at 'https://jpasholk.com/jekyll-uikit/archive/' was loaded over HTTPS, but requested an insecure prefetch resource 'http://jpasholk.com/jekyll-uikit/'. This request has been blocked; the content must be served over HTTPS.`

**Comment by jpasholk** [comment]
Seems like @mwoolweaver has this fixed on his fork, still not exactly sure what fixed it. Merged with his to solve the issue for now.
