### ISSUE TITLE
Get Google Analytics to respect my conditional statement

### ISSUE THREAD

**Issue by jpasholk** [jpasholk/jekyll-uikit#17]
This doesn't seem to be working:

`{% if jekyll.environment == "production" and site.google_analytics %}
	
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		ga('create', '{{ site.google_analytics }}', 'auto');
		ga('send', 'pageview');
	</script>
	
{% endif %}`

Any ideas?

**Comment by kenman345** [comment]
make sure your jekyll environemnt is actually set properly.

for my site, we do this:
```liquid
{% if site.google_analytics and site.GH_ENV == 'gh_pages' %}
	<!-- Google Analytics -->
	<link rel="preconnect" href="https://www.google-analytics.com/analytics.js" crossorigin>
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		ga('create', '{{ site.google_analytics }}', 'auto');
		ga('send', 'pageview');
	</script>
	<!-- End Google Analytics -->
{% endif %}
```

This basically ensures it only gets added when its on github.

**Comment by jpasholk** [comment]
Hm, would it matter that I'm not using the gh-pages branch tho?

**Comment by jpasholk** [comment]
Right now there is no GA tag, so it shouldn't be adding the code, but it is. Could it be because it's there in the config, even though there's no value?

**Comment by kenman345** [comment]
Yes, always a possibility. Try 
```liquid
{% assign GA = site.google_analytics | default: ‘’ %}
{% if GA != ‘’ and Jekyll.environment == ‘production’ %}
```

**Comment by kenman345** [comment]
My phone seems to have odd single quotes but try something along those lines to see if perhaps that fixes things.

**Comment by jpasholk** [comment]
Okay I'll try that in the morning. Just about to pass out now!

Thanks again man!
