### ISSUE TITLE
shouldnt this be based on a _config.yml setting?

### ISSUE THREAD

**Issue by kenman345** [jpasholk/jekyll-uikit#24]
https://github.com/jpasholk/jekyll-uikit/blob/3854c03490af4844705f6a9865ae8ee958f2fe05/_includes/head.html#L76

**Comment by jpasholk** [comment]
Yeah, I don’t know why it’s not. 

I’ve taken a small break from this project - but I think I have the time and energy to continue.

**Comment by jpasholk** [comment]
fixed in #27
