### ISSUE TITLE
Form not working. 

### ISSUE THREAD

**Issue by jpasholk** [jpasholk/jekyll-uikit#31]
Getting a 'Method Not Allowed' error.

!['Method Not Allowed' error.](https://i.imgur.com/c3JgLoa.png)

**Comment by jpasholk** [comment]
@daviddarnes Do you know what would cause this?

**Comment by daviddarnes** [comment]
@jpasholk have you set the email in the config?

**Comment by jpasholk** [comment]
Hm, I don’t think I did!!

**Comment by jpasholk** [comment]
I got it working, but it seems to be redirecting to a /thanks/ page that doesn't exist! Time to make one. :)

![Screenshot](https://user-images.githubusercontent.com/28698431/46958901-af7d0500-d04f-11e8-9497-fd208efd6bbb.png)

**Comment by daviddarnes** [comment]
@jpasholk oops! Sorry, I forgot about that. The include actually has an option to set that if someone wants to use a different thank you URL with `thanks_url="/some-other-page/"`. Probably should add that to the documentation for it

**Comment by jpasholk** [comment]
I’ll add that to the docs!
