### ISSUE TITLE
Form Submit button styling broken

### ISSUE THREAD

**Issue by jpasholk** [jpasholk/jekyll-uikit#34]
When viewing the form on mobile, the styling is broken.

Browsers tested:

* Safari
* Chrome
* Firefox
* Brave

![Screenshot of issue](https://i.imgur.com/edlM7nJ.jpg)

**Comment by daviddarnes** [comment]
Seems as though input elements with button classes applied don't get their appearance reset, the submit button needs `-webkit-appearance: none` to remove the odd looking iOS Safari styles

**Comment by jpasholk** [comment]
Would I use something like this?

```
input[type=submit] {
  -webkit-appearance: none;
}
```

Or use a class?

```
.button {
  -webkit-appearance: none;
}
```

I guess I could just try both, lol.

**Comment by daviddarnes** [comment]
It’s the input one, but there’s no harm applying it to both. I would’ve made a pull request but I don’t know where to put these extra styles

**Comment by jpasholk** [comment]
It's in `_includes/head.html`! Maybe I should break that out into its own file now... lol

**Comment by daviddarnes** [comment]
Probably should create a `assets/css/theme-overrides.scss` file

**Comment by jpasholk** [comment]
Hm, seems to be still broken here. Completely clueless here on how to fix it... 

:(

**Comment by jpasholk** [comment]
Yay! I fixed it with an inline style tag in the head... wtf tho man. lol
